/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'feedback',
    path: '/feedback',
    component: 'layout.base$view.feedback',
    meta: {
      title: 'feedback',
      i18nKey: 'route.feedback',
      icon: 'mdi:message-text-outline',
      order: 5
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'queues',
    path: '/queues',
    component: 'layout.base$view.queues',
    meta: {
      title: 'queues',
      i18nKey: 'route.queues',
      icon: 'mdi:account-group-outline',
      order: 3
    }
  },
  {
    name: 'recommend',
    path: '/recommend',
    component: 'layout.base$view.recommend',
    meta: {
      title: 'recommend',
      i18nKey: 'route.recommend',
      icon: 'mdi:chart-timeline-variant',
      order: 4
    }
  },
  {
    name: 'settings',
    path: '/settings',
    component: 'layout.base$view.settings',
    meta: {
      title: 'settings',
      i18nKey: 'route.settings',
      icon: 'mdi:cog-outline',
      order: 7
    }
  },
  {
    name: 'stalls',
    path: '/stalls',
    component: 'layout.base$view.stalls',
    meta: {
      title: 'stalls',
      i18nKey: 'route.stalls',
      icon: 'mdi:storefront-outline',
      order: 2
    }
  },
  {
    name: 'users',
    path: '/users',
    component: 'layout.base$view.users',
    meta: {
      title: 'users',
      i18nKey: 'route.users',
      icon: 'mdi:account-multiple-outline',
      order: 6
    }
  }
];
